### ISSUE TITLE
Investigate timed out tests

### ISSUE THREAD

**Issue by Richard87** [equinor/radix-operator#1023]
Figure out why these tests sometimes doesnt complete

```
time="2023-12-29T12:22:47Z" level=info msg="Setting up event handlers" radixOperatorComponent=registration-controller
time="2023-12-29T12:22:47Z" level=info msg="Waiting for informer caches to sync" radixOperatorComponent=registration-controller
time="2023-12-29T12:22:47Z" level=info msg="Starting workers" radixOperatorComponent=registration-controller
panic: test timed out after 2m0s
running tests:
Test_Controller_Calls_Handler (2m0s)
...
goroutine 22 [chan receive]:
github.com/equinor/radix-operator/radix-operator/registration.Test_Controller_Calls_Handler(0xc000276b60)
/home/runner/work/radix-operator/radix-operator/radix-operator/registration/controller_test.go:75 +0x505
testing.tRunner(0xc000276b60, 0x1c6aec8)
/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1595 +0xff
created by testing.(*T).Run in goroutine 1
/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1648 +0x3ad

```

```
time="2023-12-29T07:34:19Z" level=info msg="Setting up event handlers" radixOperatorComponent=registration-controller
time="2023-12-29T07:34:19Z" level=info msg="Waiting for informer caches to sync" radixOperatorComponent=registration-controller
time="2023-12-29T07:34:19Z" level=info msg="Starting workers" radixOperatorComponent=registration-controller
panic: test timed out after 2m0s
running tests:
Test_Controller_Calls_Handler (2m0s)
...
goroutine 22 [chan receive]:
github.com/equinor/radix-operator/radix-operator/registration.Test_Controller_Calls_Handler(0xc000276b60)
/home/runner/work/radix-operator/radix-operator/radix-operator/registration/controller_test.go:75 +0x505
testing.tRunner(0xc000276b60, 0x1c6aec8)
/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1595 +0xff
created by testing.(*T).Run in goroutine 1
/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1648 +0x3ad
```

```
time="2023-12-29T12:29:27Z" level=error msg="namespaces \"test-app-qa\" already exists"
time="2023-12-29T12:29:27Z" level=info msg="Setting up event handlers" radixOperatorComponent=deployment-controller
time="2023-12-29T12:29:27Z" level=info msg="Waiting for informer caches to sync" radixOperatorComponent=deployment-controller
time="2023-12-29T12:29:27Z" level=info msg="Starting workers" radixOperatorComponent=deployment-controller
panic: test timed out after 2m0s
running tests:
Test_Controller_Calls_Handler (2m0s)
...
goroutine 35 [chan receive, 2 minutes]:
github.com/equinor/radix-operator/radix-operator/deployment.Test_Controller_Calls_Handler(0xc000007860)
/home/runner/work/radix-operator/radix-operator/radix-operator/deployment/controller_test.go:99 +0x625
testing.tRunner(0xc000007860, 0x1dd2498)
/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1595 +0xff
created by testing.(*T).Run in goroutine 1
/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1648 +0x3ad
```

**Comment by Richard87** [comment]
This seems to be the issue:
```
?   	github.com/equinor/radix-operator/radix-operator/batch/internal	[no test files]
ok  	github.com/equinor/radix-operator/radix-operator/batch	0.116s
?   	github.com/equinor/radix-operator/radix-operator/config	[no test files]
?   	github.com/equinor/radix-operator/radix-operator/dnsalias/internal	[no test files]
ok  	github.com/equinor/radix-operator/radix-operator/common	1.047s
time="2023-12-29T15:47:02Z" level=info msg="Setting up event handlers" radixOperatorComponent=deployment-controller
time="2023-12-29T15:47:02Z" level=error msg="namespaces \"test-app-qa\" already exists"
time="2023-12-29T15:47:02Z" level=info msg="Waiting for informer caches to sync" radixOperatorComponent=deployment-controller
time="2023-12-29T15:47:03Z" level=info msg="Starting workers" radixOperatorComponent=deployment-controller
time="2023-12-29T15:47:03Z" level=info msg="Successfully synced test-app-qa/qa-imagetag-91fj93po" radixOperatorComponent=deployment-controller
--- FAIL: Test_Controller_Calls_Handler (5.00s)
    controller_test.go:101: 
        	Error Trace:	/home/runner/work/radix-operator/radix-operator/radix-operator/deployment/controller_test.go:101
        	Error:      	Received unexpected error:
        	            	context deadline exceeded
        	Test:       	Test_Controller_Calls_Handler
E1229 15:47:07.988[62](https://github.com/equinor/radix-operator/actions/runs/7357957421/job/20030424379#step:5:63)4   127[64](https://github.com/equinor/radix-operator/actions/runs/7357957421/job/20030424379#step:5:65) handler.go:145] radix deployment nonexisting-rd in work queue no longer exists
E1229 15:47:07.988[73](https://github.com/equinor/radix-operator/actions/runs/7357957421/job/20030424379#step:5:74)8   12[76](https://github.com/equinor/radix-operator/actions/runs/7357957421/job/20030424379#step:5:77)4 handler.go:164] failed to get RadixRegistartion object: radixregistrations.radix.equinor.com "" not found
FAIL
FAIL	github.com/equinor/radix-operator/radix-operator/deployment	5.024s
ok  	github.com/equinor/radix-operator/radix-operator/dnsalias	0.189s
ok  	github.com/equinor/radix-operator/radix-operator/environment	0.014s
ok  	github.com/equinor/radix-operator/radix-operator/job	0.130s
time="2023-12-29T15:47:05Z" level=info msg="Setting up event handlers" radixOperatorComponent=registration-controller
time="2023-12-29T15:47:05Z" level=info msg="Waiting for informer caches to sync" radixOperatorComponent=registration-controller
time="2023-12-29T15:47:05Z" level=info msg="Starting workers" radixOperatorComponent=registration-controller
time="2023-12-29T15:47:05Z" level=info msg="Created namespace testapp-app" registrationName=testapp
time="2023-12-29T15:47:05Z" level=warning msg="Not all limits are defined for the Operator, so no limitrange will be put on namespace testapp-app"
time="2023-12-29T15:47:06Z" level=info msg="Created secret: git-ssh-keys in namespace testapp-app"
time="2023-12-29T15:47:06Z" level=error msg="Failed to get radix-sp-acr-azure secret from default. secrets \"radix-sp-acr-azure\" not found"
time="2023-12-29T15:47:06Z" level=warning msg="Failed to apply service principle acr secrets (radix-sp-acr-azure, radix-sp-buildah-azure) to namespace testapp-app"
time="2023-12-29T15:47:06Z" level=info msg="Successfully synced testapp" radixOperatorComponent=registration-controller
--- FAIL: Test_Controller_Calls_Handler (5.00s)
    controller_test.go:[78](https://github.com/equinor/radix-operator/actions/runs/7357957421/job/20030424379#step:5:79): 
        	Error Trace:	/home/runner/work/radix-operator/radix-operator/radix-operator/registration/controller_test.go:78
        	Error:      	Received unexpected error:
        	            	context deadline exceeded
        	Test:       	Test_Controller_Calls_Handler
FAIL
FAIL	github.com/equinor/radix-operator/radix-operator/registration	5.014s
FAIL
```

**Comment by Richard87** [comment]
Test falied with custom timeout:
```
time="2024-01-08T07:43:39Z" level=info msg="Setting up event handlers" radixOperatorComponent=registration-controller
time="2024-01-08T07:43:39Z" level=info msg="Waiting for informer caches to sync" radixOperatorComponent=registration-controller
time="2024-01-08T07:43:39Z" level=info msg="Starting workers" radixOperatorComponent=registration-controller
--- FAIL: Test_Controller_Calls_Handler (5.00s)
    controller_test.go:79: 
        	Error Trace:	/home/runner/work/radix-operator/radix-operator/radix-operator/registration/controller_test.go:79
        	Error:      	Received unexpected error:
        	            	context deadline exceeded
        	Test:       	Test_Controller_Calls_Handler
FAIL
FAIL	github.com/equinor/radix-operator/radix-operator/registration	5.016s
FAIL
Error: Process completed with exit code 1.
```
